package ru.stanise.animebrowsing.ui.model

import ru.stanise.animebrowsing.AnimeListQuery

val availableGenres = listOf(
	AnimeListQuery.Genre("27", "Shounen", "Сёнен"),
	AnimeListQuery.Genre("25", "Shoujo", "Сёдзё"),
	AnimeListQuery.Genre("42", "Seinen", "Сэйнэн"),
	AnimeListQuery.Genre("43", "Josei", "Дзёсей"),
	AnimeListQuery.Genre("4", "Comedy", "Комедия"),
	AnimeListQuery.Genre("9", "Ecchi", "Этти"),
	AnimeListQuery.Genre("10", "Fantasy", "Фэнтези"),
	AnimeListQuery.Genre("14", "Horror", "Ужасы"),
	AnimeListQuery.Genre("1", "Action", "Экшен"),
	AnimeListQuery.Genre("36", "Slice of Life", "Повседневность"),
	AnimeListQuery.Genre("22", "Romance", "Романтика"),
	AnimeListQuery.Genre("7", "Mystery", "Тайна"),
	AnimeListQuery.Genre("117", "Suspense", "Триллер"),
	AnimeListQuery.Genre("24", "Sci-Fi", "Фантастика"),
	AnimeListQuery.Genre("30", "Sports", "Спорт"),
	AnimeListQuery.Genre("37", "Supernatural", "Сверхъестественное"),
	AnimeListQuery.Genre("8", "Drama", "Драма"),
	AnimeListQuery.Genre("2", "Adventure", "Приключения"),
	AnimeListQuery.Genre("12", "Hentai", "Хентай"),
	AnimeListQuery.Genre("20", "Parody", "Пародия"),
	AnimeListQuery.Genre("38", "Military", "Военное"),
	AnimeListQuery.Genre("40", "Psychological", "Психологическое"),
	AnimeListQuery.Genre("141", "Survival", "Выживание"),
	AnimeListQuery.Genre("106", "Reincarnation", "Реинкарнация"),
	AnimeListQuery.Genre("147", "Medical", "Медицина"),
	AnimeListQuery.Genre("17", "Martial Arts", "Боевые искусства"),
	AnimeListQuery.Genre("18", "Mecha", "Меха"),
	AnimeListQuery.Genre("21", "Samurai", "Самураи"),
	AnimeListQuery.Genre("23", "School", "Школа"),
	AnimeListQuery.Genre("29", "Space", "Космос"),
	AnimeListQuery.Genre("35", "Harem", "Гарем"),
	AnimeListQuery.Genre("31", "Super Power", "Супер сила"),
	AnimeListQuery.Genre("13", "Historical", "Исторический"),
	AnimeListQuery.Genre("3", "Racing", "Гонки"),
	AnimeListQuery.Genre("139", "Workplace", "Работа"),
	AnimeListQuery.Genre("114", "Award Winning", "Удостоено наград"),
	AnimeListQuery.Genre("105", "Gore", "Жестокость"),
	AnimeListQuery.Genre("111", "Time Travel", "Путешествие во времени"),
	AnimeListQuery.Genre("39", "Detective", "Детектив"),
	AnimeListQuery.Genre("130", "Isekai", "Исэкай"),
)