package ru.stanise.animebrowsing.ui.model

import ru.stanise.animebrowsing.dto.Genre

val availableGenres = setOf(
	Genre(1, "Action"),
	Genre(2, "Adventure"),
	Genre(46, "Award Winning"),
	Genre(4, "Comedy"),
	Genre(8, "Drama"),
	Genre(10, "Fantasy"),
	Genre(14, "Horror"),
	Genre(7, "Mystery"),
	Genre(22, "Romance"),
	Genre(24, "Sci-Fi"),
	Genre(36, "Slice of Life"),
	Genre(30, "Sports"),
	Genre(37, "Supernatural"),
	Genre(41, "Suspense"),
	Genre(9, "Ecchi"),
	Genre(12, "Hentai"),
	Genre(39, "Detective"),
	Genre(57, "Gag Humor"),
	Genre(58, "Gore"),
	Genre(35, "Harem"),
	Genre(13, "Historical"),
	Genre(62, "Isekai"),
	Genre(17, "Martial Arts"),
	Genre(18, "Mecha"),
	Genre(67, "Medical"),
	Genre(38, "Military"),
	Genre(6, "Mythology"),
	Genre(20, "Parody"),
	Genre(40, "Psychological"),
	Genre(3, "Racing"),
	Genre(72, "Reincarnation"),
	Genre(21, "Samurai"),
	Genre(23, "School"),
	Genre(29, "Space"),
	Genre(31, "Super Power"),
	Genre(76, "Survival"),
	Genre(78, "Time Travel"),
	Genre(32, "Vampire"),
	Genre(42, "Seinen"),
	Genre(64, "Love Polygon"),
	Genre(27, "Shounen")
)